Bug/aggregate bids
cryptonative-ch/mesa-interface pull request #276
Opened 2021-06-18 19:44 UTC by hhamud

---
name: Pull Request
about: Create a pull request for this project

---

## Description
* Closes #246 
* Closes #269 

## Motivation and Context

## How Has This Been Tested?
Tested Manually

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-06-18 20:09 UTC, rossneilson approved these changes
Looks good to me.
Nice to see it aggregate bids.
If the information is there then it could be good to have an option to show more info of the individual purchases in a drop down menu.

Although I did find another issue, it seems once funds are withdrawn they are not removed from the UI or marked as withdrawn.

2021-06-18 21:32 UTC, adamazad requested changes

2021-06-18 21:32 UTC, adamazad commented on src/views/Sale/components/SelfBidList/index.tsx
> +  console.log(bids)
Remove logs

2021-06-18 21:32 UTC, adamazad commented on src/views/Sale/components/SelfBidList/index.tsx
> +  console.log(bids)
Remove logs

2021-06-21 09:38 UTC, hhamud commented on src/hooks/useBids.ts
>  export function useBids(saleId: string, saleType: SaleType): UseBidsReturn {
I was using the mesa sdk originally. I can switch it out for those hook's you've made later on

2021-06-21 09:39 UTC, hhamud commented on src/hooks/useTokenClaim.ts
> -  const [withdrawError, setWithdrawError] = useState<MetaMaskError>()
I will make a separate file for the error types

2021-06-21 10:30 UTC, merged